import unittest
import std/math
import std/strutils
import std/json
import std/os
import ../src/observy/anyvalue
import ../src/observy/traces
import ../src/observy/json_encode

suite "hex encoding":
  test "hexEncodeTraceId produces 32 lowercase hex chars":
    var id: TraceId
    for i in 0 ..< 16: id[i] = byte(i)
    let s = hexEncodeTraceId(id)
    check s.len == 32
    check s == "000102030405060708090a0b0c0d0e0f"

  test "hexEncodeTraceId all-zero is 32 zeros":
    var id: TraceId
    check hexEncodeTraceId(id) == "0" & "0".repeat(31)

  test "hexEncodeTraceId all-ones (0xFF)":
    var id: TraceId
    for i in 0 ..< 16: id[i] = 0xFF'u8
    check hexEncodeTraceId(id) == "f".repeat(32)

  test "hexEncodeSpanId produces 16 lowercase hex chars":
    var id: SpanId
    for i in 0 ..< 8: id[i] = byte(i + 1)
    let s = hexEncodeSpanId(id)
    check s.len == 16
    check s == "0102030405060708"

  test "hexEncodeSpanId uses lowercase (not uppercase)":
    var id: SpanId
    id[0] = 0xAB'u8
    id[1] = 0xCD'u8
    let s = hexEncodeSpanId(id)
    check s[0..3] == "abcd"

suite "base64Encode":
  test "empty bytes produces empty string":
    check base64Encode(@[]) == ""

  test "known vector: [0x01, 0x02, 0x03] = AQID":
    check base64Encode(@[0x01'u8, 0x02, 0x03]) == "AQID"

  test "no line breaks in output":
    let data = newSeq[byte](60)
    check base64Encode(data).find('\n') < 0
    check base64Encode(data).find('\r') < 0

suite "jsonEncodeInt64 / jsonEncodeUint64":
  test "int64 positive is quoted string":
    check jsonEncodeInt64(42) == "\"42\""

  test "int64 negative is quoted string":
    check jsonEncodeInt64(-1) == "\"-1\""

  test "int64 min value":
    check jsonEncodeInt64(low(int64)) == "\"-9223372036854775808\""

  test "int64 max value":
    check jsonEncodeInt64(high(int64)) == "\"9223372036854775807\""

  test "uint64 large value is quoted":
    check jsonEncodeUint64(high(uint64)) == "\"18446744073709551615\""

  test "uint64 zero is quoted":
    check jsonEncodeUint64(0'u64) == "\"0\""

suite "jsonEncodeAnyValue":
  test "string value":
    let v = AnyValue(kind: avString, strVal: "hello")
    check jsonEncodeAnyValue(v) == "{\"stringValue\":\"hello\"}"

  test "bool true":
    let v = AnyValue(kind: avBool, boolVal: true)
    check jsonEncodeAnyValue(v) == "{\"boolValue\":true}"

  test "bool false":
    let v = AnyValue(kind: avBool, boolVal: false)
    check jsonEncodeAnyValue(v) == "{\"boolValue\":false}"

  test "int64 value is quoted string":
    let v = AnyValue(kind: avInt, intVal: 123'i64)
    check jsonEncodeAnyValue(v) == "{\"intValue\":\"123\"}"

  test "double finite":
    let v = AnyValue(kind: avDouble, dblVal: 3.14)
    check jsonEncodeAnyValue(v) == "{\"doubleValue\":3.14}"

  test "double NaN is string":
    let v = AnyValue(kind: avDouble, dblVal: NaN)
    check jsonEncodeAnyValue(v) == "{\"doubleValue\":\"NaN\"}"

  test "double Inf is string":
    let v = AnyValue(kind: avDouble, dblVal: Inf)
    check jsonEncodeAnyValue(v) == "{\"doubleValue\":\"Infinity\"}"

  test "double -Inf is string":
    let v = AnyValue(kind: avDouble, dblVal: NegInf)
    check jsonEncodeAnyValue(v) == "{\"doubleValue\":\"-Infinity\"}"

  test "bytes uses base64 (NOT hex)":
    let v = AnyValue(kind: avBytes, bytesVal: @[0x01'u8, 0x02, 0x03])
    let j = jsonEncodeAnyValue(v)
    check j.find("\"bytesValue\"") >= 0
    check j.find("AQID") >= 0  # base64 of [0x01, 0x02, 0x03]

  test "string value escapes double quote":
    let v = AnyValue(kind: avString, strVal: "say \"hi\"")
    check jsonEncodeAnyValue(v) == "{\"stringValue\":\"say \\\"hi\\\"\"}"

suite "jsonEncodeKVList":
  test "empty list is []":
    check jsonEncodeKVList(@[]) == "[]"

  test "single entry":
    let kvs = @[KeyValue(key: "k", value: AnyValue(kind: avString, strVal: "v"))]
    check jsonEncodeKVList(kvs) == "[{\"key\":\"k\",\"value\":{\"stringValue\":\"v\"}}]"

  test "two entries comma-separated":
    let kvs = @[
      KeyValue(key: "a", value: AnyValue(kind: avInt, intVal: 1)),
      KeyValue(key: "b", value: AnyValue(kind: avBool, boolVal: true)),
    ]
    let j = jsonEncodeKVList(kvs)
    check j.find(",") >= 0
    check j.find("\"a\"") >= 0
    check j.find("\"b\"") >= 0

suite "TraceId and SpanId not base64":
  test "hexEncodeTraceId output contains no = (base64 padding char)":
    var id: TraceId
    for i in 0 ..< 16: id[i] = 0xAB'u8
    check hexEncodeTraceId(id).find('=') < 0

  test "hexEncodeSpanId output contains no = (base64 padding char)":
    var id: SpanId
    for i in 0 ..< 8: id[i] = 0xCD'u8
    check hexEncodeSpanId(id).find('=') < 0

# ---------------------------------------------------------------------------
# Golden-file JSON fixture tests
# Verify the Nim JSON encoder produces values that match the reference fixtures
# in tests/fixtures/json/ (generated by tools/gen_fixtures.py)
# ---------------------------------------------------------------------------

proc parseHexByte(s: string; i: int): byte =
  byte(parseHexInt(s[i*2 ..< i*2+2]))

suite "golden JSON fixtures — trace_id_hex.json":
  test "traceId is 32 lowercase hex chars (not base64)":
    # Same TraceId as in trace_id_hex.json
    var tid: TraceId
    let hex = "4bf92f3577b34da6a3ce929d0e0e4736"
    for i in 0 ..< 16: tid[i] = parseHexByte(hex, i)
    let encoded = hexEncodeTraceId(tid)
    check encoded == hex
    check encoded.len == 32
    check encoded.find('=') < 0   # no base64 padding
    for c in encoded: check c in {'0'..'9', 'a'..'f'}

  test "spanId is 16 lowercase hex chars (not base64)":
    var sid: SpanId
    let hex = "00f067aa0ba902b7"
    for i in 0 ..< 8: sid[i] = parseHexByte(hex, i)
    let encoded = hexEncodeSpanId(sid)
    check encoded == hex
    check encoded.len == 16
    check encoded.find('=') < 0
    for c in encoded: check c in {'0'..'9', 'a'..'f'}

  test "fixture file confirms hex encoding":
    let j = parseJson(readFile("tests/fixtures/json/trace_id_hex.json"))
    check j["traceId"].getStr() == "4bf92f3577b34da6a3ce929d0e0e4736"
    check j["traceId"].getStr().len == 32
    check j["spanId"].getStr() == "00f067aa0ba902b7"
    check j["spanId"].getStr().len == 16

suite "golden JSON fixtures — bytes_base64.json":
  test "bytes attribute value is standard base64 (not hex, no line breaks)":
    let data = @[0x01'u8, 0x02, 0x03, 0x04]
    let encoded = base64Encode(data)
    check encoded == "AQIDBA=="
    check encoded.find('\n') < 0
    check encoded.find('\r') < 0

  test "fixture file confirms base64 encoding":
    let j = parseJson(readFile("tests/fixtures/json/bytes_base64.json"))
    check j["attributes"][0]["value"]["bytesValue"].getStr() == "AQIDBA=="

suite "golden JSON fixtures — int64_string.json":
  test "startTimeUnixNano is a JSON string not a JSON number":
    let encoded = jsonEncodeUint64(1_000_000_000_000_000_000'u64)
    check encoded == "\"1000000000000000000\""

  test "intValue in AnyValue is a quoted string":
    let v = AnyValue(kind: avInt, intVal: 9_223_372_036_854_775_807'i64)
    let j = jsonEncodeAnyValue(v)
    let parsed = parseJson(j)
    check parsed["intValue"].kind == JString   # must be a string, not JInt
    check parsed["intValue"].getStr() == "9223372036854775807"

  test "fixture file confirms int64 is a JSON string":
    let j = parseJson(readFile("tests/fixtures/json/int64_string.json"))
    check j["startTimeUnixNano"].kind == JString
    check j["startTimeUnixNano"].getStr() == "1000000000000000000"
    # "intAttribute" is a synthetic documentation key in the fixture (not an OTLP field name).
    check j["intAttribute"]["intValue"].kind == JString

suite "golden JSON fixtures — full_span.json":
  test "all AnyValue kinds encode to correct OTLP-JSON field names":
    # Verify the JSON field names per signal type
    check parseJson(jsonEncodeAnyValue(AnyValue(kind: avString, strVal: "x"))).hasKey("stringValue")
    check parseJson(jsonEncodeAnyValue(AnyValue(kind: avBool, boolVal: true))).hasKey("boolValue")
    check parseJson(jsonEncodeAnyValue(AnyValue(kind: avInt, intVal: 1))).hasKey("intValue")
    check parseJson(jsonEncodeAnyValue(AnyValue(kind: avDouble, dblVal: 1.0))).hasKey("doubleValue")
    check parseJson(jsonEncodeAnyValue(AnyValue(kind: avBytes, bytesVal: @[0x01'u8]))).hasKey("bytesValue")
    check parseJson(jsonEncodeAnyValue(AnyValue(kind: avArray, arrayVal: @[]))).hasKey("arrayValue")
    check parseJson(jsonEncodeAnyValue(AnyValue(kind: avKvList, kvlistVal: @[]))).hasKey("kvlistValue")

  test "fixture file — traceId and spanId are lowercase hex":
    let j = parseJson(readFile("tests/fixtures/json/full_span.json"))
    let tid = j["traceId"].getStr()
    let sid = j["spanId"].getStr()
    check tid.len == 32
    check sid.len == 16
    for c in tid: check c in {'0'..'9', 'a'..'f'}
    for c in sid: check c in {'0'..'9', 'a'..'f'}

  test "fixture file — startTimeUnixNano is a JSON string":
    let j = parseJson(readFile("tests/fixtures/json/full_span.json"))
    check j["startTimeUnixNano"].kind == JString

  test "fixture file — intValue attribute is a quoted string":
    let j = parseJson(readFile("tests/fixtures/json/full_span.json"))
    # http.status_code = 201 is intValue
    let attrs = j["attributes"]
    var found = false
    for attr in attrs:
      if attr["key"].getStr() == "http.status_code":
        check attr["value"]["intValue"].kind == JString
        check attr["value"]["intValue"].getStr() == "201"
        found = true
    check found

  test "fixture file — bytesValue attribute is base64":
    let j = parseJson(readFile("tests/fixtures/json/full_span.json"))
    let attrs = j["attributes"]
    var found = false
    for attr in attrs:
      if attr["key"].getStr() == "request.id":
        check attr["value"]["bytesValue"].getStr() == "AQIDBA=="
        found = true
    check found

  test "fixture file — kind is an integer (OTLP-JSON uses enum int not name)":
    # OTLP-JSON maps enums to their integer value, not the name string.
    let j = parseJson(readFile("tests/fixtures/json/full_span.json"))
    check j["kind"].kind == JInt
    check j["kind"].getInt() == 2  # SpanKind.SERVER

suite "golden JSON fixtures — span_id_hex.json":
  test "fixture file — spanId is 16 lowercase hex chars":
    let j = parseJson(readFile("tests/fixtures/json/span_id_hex.json"))
    let sid = j["spanId"].getStr()
    check sid.len == 16
    check sid == "00f067aa0ba902b7"
    for c in sid: check c in {'0'..'9', 'a'..'f'}

  test "spanId from model matches fixture":
    # Construct the same SpanId used in gen_fixtures.py and verify encoder output matches
    var sid: SpanId
    let hex = "00f067aa0ba902b7"
    for i in 0 ..< 8: sid[i] = parseHexByte(hex, i)
    check hexEncodeSpanId(sid) == hex
